import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider/provider";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Navbar from "@/components/navbar";
import HeroSection from "@/components/hero";
import FeaturedProducts from "@/components/feature-product";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Navbar />
          <HeroSection />
          <FeaturedProducts />
          {children}
        </Provider>
      </body>
    </html>
  );
}
